Repository zaleos/sipplauncher, pull requests merged in 2021-05, with the labels that each got.

#77 Auto-deploy docs
  .github/workflows/doc.yaml
  requirements_docs.txt
Labels: size/M

#76 Revert SIPpTest changes
  .github/workflows/ci.yaml
  Makefile
  sipplauncher/GlobalTest.py
  sipplauncher/Run.py
  sipplauncher/Test.py
  sipplauncher/TestPool.py
  sipplauncher/utils/Defaults.py
  test/test_sipplauncher_PysippProcess.py
  test/test_sipplauncher_Run.py
  test/test_sipplauncher_Run_states.py
  test/test_sipplauncher_Test.py
  test/test_sipplauncher_Test_chdir.py
  test/test_sipplauncher_Test_keyword_replacement.py
  test/test_sipplauncher_signal.py
Labels: size/L

#79 Force documentation website update
  docs/dependencies.md
Labels: size/XS

#80 Fix dependency
  requirements.txt
Labels: size/XS
