Repository zaleos/sipplauncher, pull requests merged in 2021-03, with the labels that each got.

#69 Feature - Add run_id_number
  .gitignore
  docs/user_guide.md
  sipplauncher/Test.py
  sipplauncher/utils/Defaults.py
Labels: size/S

#70 Remove all the default behaviors of sipp
  docs/user_guide.md
  sipplauncher/PysippProcess.py
  sipplauncher/utils/Init.py
Labels: size/XS

#71 Renaming property
  sipplauncher/PysippProcess.py
  sipplauncher/Test.py
  sipplauncher/UA.py
  sipplauncher/utils/Defaults.py
Labels: size/M

#72 Refactor SIPpTest class
  sipplauncher/GlobalTest.py
  sipplauncher/Run.py
  sipplauncher/Test.py
  sipplauncher/TestPool.py
  test/test_sipplauncher_PysippProcess.py
  test/test_sipplauncher_Test.py
  test/test_sipplauncher_Test_chdir.py
  test/test_sipplauncher_Test_keyword_replacement.py
Labels: size/M
